M48
; DRILL file {KiCad 9.0.2} date 2025-07-01T21:57:18-0500
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-07-01T21:57:18-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.2
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C2.100
%
G90
G05
T1
X198.345Y-119.4
X198.345Y-125.18
T2
X195.85Y-91.55
X195.85Y-130.1
X241.5Y-91.4
X241.5Y-130.05
M30
